### ISSUE TITLE
small glitches

### ISSUE THREAD

**Issue by kklepper** [MfN-Berlin/docker-selenium#1]
in build.sh change

#! /bin/bash
to
#! /bin/sh

so it will run with alpine (has no bash). Also correct

source config.ini

to

source ./config.ini

same with run.sh

**Comment by alvarosaurus** [comment]
source ./config.ini does not find the file (in Debian)
Why not install bash? https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/

**Comment by kklepper** [comment]
Thank you very much! Didn't know this.
